INSERT INTO country (code,name,emoji,continent) VALUES
('AL','Albanie','🇦🇱','Europe'),
('AT','Autriche','🇦🇹','Europe'),
('BY','Biélorussie','🇧🇾','Europe'),
('BE','Belgique','🇧🇪','Europe'),
('BA','Bosnie-Herzégovine','🇧🇦','Europe'),
('BG','Bulgarie','🇧🇬','Europe'),
('HR','Croatie','🇭🇷','Europe'),
('CY','Chypre','🇨🇾','Europe'),
('CZ','République tchèque','🇨🇿','Europe'),
('DK','Danemark','🇩🇰','Europe'),
('EE','Estonie','🇪🇪','Europe'),
('FI','Finlande','🇫🇮','Europe'),
('FR','France','🇫🇷','Europe'),
('DE','Allemagne','🇩🇪','Europe'),
('GR','Grèce','🇬🇷','Europe'),
('HU','Hongrie','🇭🇺','Europe'),
('IS','Islande','🇮🇸','Europe'),
('IE','Irlande','🇮🇪','Europe'),
('IT','Italie','🇮🇹','Europe'),
('LV','Lettonie','🇱🇻','Europe'),
('LI','Liechtenstein','🇱🇮','Europe'),
('LT','Lituanie','🇱🇹','Europe'),
('LU','Luxembourg','🇱🇺','Europe'),
('MT','Malte','🇲🇹','Europe'),
('MD','Moldavie','🇲🇩','Europe'),
('MC','Monaco','🇲🇨','Europe'),
('ME','Monténégro','🇲🇪','Europe'),
('NL','Pays-Bas','🇳🇱','Europe'),
('MK','Macédoine du Nord','🇲🇰','Europe'),
('NO','Norvège','🇳🇴','Europe'),
('PL','Pologne','🇵🇱','Europe'),
('PT','Portugal','🇵🇹','Europe'),
('RO','Roumanie','🇷🇴','Europe'),
('RU','Russie','🇷🇺','Europe'),
('SM','Saint-Marin','🇸🇲','Europe'),
('RS','Serbie','🇷🇸','Europe'),
('SK','Slovaquie','🇸🇰','Europe'),
('SI','Slovénie','🇸🇮','Europe'),
('ES','Espagne','🇪🇸','Europe'),
('SE','Suède','🇸🇪','Europe'),
('CH','Suisse','🇨🇭','Europe'),
('TR','Turquie','🇹🇷','Europe'),
('UA','Ukraine','🇺🇦','Europe'),
('GB','Royaume-Uni','🇬🇧','Europe'),
('AG','Antigua-et-Barbuda','🇦🇬','North America'),
('BS','Bahamas','🇧🇸','North America'),
('BB','Barbade','🇧🇧','North America'),
('BZ','Belize','🇧🇿','North America'),
('CA','Canada','🇨🇦','North America'),
('CR','Costa Rica','🇨🇷','North America'),
('CU','Cuba','🇨🇺','North America'),
('DM','Dominique','🇩🇲','North America'),
('DO','République dominicaine','🇩🇴','North America'),
('SV','Salvador','🇸🇻','North America'),
('GD','Grenade','🇬🇩','North America'),
('GT','Guatemala','🇬🇹','North America'),
('HT','Haïti','🇭🇹','North America'),
('HN','Honduras','🇭🇳','North America'),
('JM','Jamaïque','🇯🇲','North America'),
('MX','Mexique','🇲🇽','North America'),
('NI','Nicaragua','🇳🇮','North America'),
('PA','Panama','🇵🇦','North America'),
('KN','Saint-Christophe-et-Niévès','🇰🇳','North America'),
('LC','Sainte-Lucie','🇱🇨','North America'),
('VC','Saint-Vincent-et-les-Grenadines','🇻🇨','North America'),
('TT','Trinité-et-Tobago','🇹🇹','North America'),
('AR','Argentine','🇦🇷','South America'),
('BO','Bolivie','🇧🇴','South America'),
('BR','Brésil','🇧🇷','South America'),
('CL','Chili','🇨🇱','South America'),
('CO','Colombie','🇨🇴','South America'),
('EC','Équateur','🇪🇨','South America'),
('GY','Guyana','🇬🇾','South America'),
('PY','Paraguay','🇵🇾','South America'),
('PE','Pérou','🇵🇪','South America'),
('SR','Suriname','🇸🇷','South America'),
('UY','Uruguay','🇺🇾','South America'),
('DZ','Algérie','🇩🇿','Africa'),
('AO','Angola','🇦🇴','Africa'),
('BJ','Bénin','🇧🇯','Africa'),
('BW','Botswana','🇧🇼','Africa'),
('BF','Burkina Faso','🇧🇫','Africa'),
('BI','Burundi','🇧🇮','Africa'),
('CM','Cameroun','🇨🇲','Africa'),
('CV','Cap-Vert','🇨🇻','Africa'),
('CF','République centrafricaine','🇨🇫','Africa'),
('TD','Tchad','🇹🇩','Africa'),
('KM','Comores','🇰🇲','Africa'),
('CG','Congo','🇨🇬','Africa'),
('CD','République démocratique du Congo','🇨🇩','Africa'),
('CI','Côte d''Ivoire','🇨🇮','Africa'),
('DJ','Djibouti','🇩🇯','Africa'),
('EG','Égypte','🇪🇬','Africa'),
('GQ','Guinée équatoriale','🇬🇶','Africa'),
('ER','Érythrée','🇪🇷','Africa'),
('SZ','Eswatini','🇸🇿','Africa'),
('ET','Éthiopie','🇪🇹','Africa'),
('GA','Gabon','🇬🇦','Africa'),
('GM','Gambie','🇬🇲','Africa'),
('GH','Ghana','🇬🇭','Africa'),
('GN','Guinée','🇬🇳','Africa'),
('GW','Guinée-Bissau','🇬🇼','Africa'),
('KE','Kenya','🇰🇪','Africa'),
('LS','Lesotho','🇱🇸','Africa'),
('LR','Libéria','🇱🇷','Africa'),
('LY','Libye','🇱🇾','Africa'),
('MG','Madagascar','🇲🇬','Africa'),
('MW','Malawi','🇲🇼','Africa'),
('ML','Mali','🇲🇱','Africa'),
('MR','Mauritanie','🇲🇷','Africa'),
('MU','Maurice','🇲🇺','Africa'),
('MA','Maroc','🇲🇦','Africa'),
('MZ','Mozambique','🇲🇿','Africa'),
('NA','Namibie','🇳🇦','Africa'),
('NE','Niger','🇳🇪','Africa'),
('NG','Nigéria','🇳🇬','Africa'),
('RW','Rwanda','🇷🇼','Africa'),
('ST','Sao Tomé-et-Principe','🇸🇹','Africa'),
('SN','Sénégal','🇸🇳','Africa'),
('SC','Seychelles','🇸🇨','Africa'),
('SL','Sierra Leone','🇸🇱','Africa'),
('SO','Somalie','🇸🇴','Africa'),
('ZA','Afrique du Sud','🇿🇦','Africa'),
('SS','Soudan du Sud','🇸🇸','Africa'),
('SD','Soudan','🇸🇩','Africa'),
('TZ','Tanzanie','🇹🇿','Africa'),
('TG','Togo','🇹🇬','Africa'),
('TN','Tunisie','🇹🇳','Africa'),
('UG','Ouganda','🇺🇬','Africa'),
('ZM','Zambie','🇿🇲','Africa'),
('AQ','Antarctique','🇦🇶','Antarctica'),
('BV','Île Bouvet','🇧🇻','Antarctica'),
('TF','Terres australes et antarctiques françaises','🇹🇫','Antarctica'),
('HM','Îles Heard-et-MacDonald','🇭🇲','Antarctica'),
('AF','Afghanistan','🇦🇫','Asia'),
('AM','Arménie','🇦🇲','Asia'),
('AZ','Azerbaïdjan','🇦🇿','Asia'),
('BH','Bahreïn','🇧🇭','Asia'),
('BD','Bangladesh','🇧🇩','Asia'),
('BT','Bhoutan','🇧🇹','Asia'),
('BN','Brunei','🇧🇳','Asia'),
('KH','Cambodge','🇰🇭','Asia'),
('CN','Chine','🇨🇳','Asia'),
('CY','Chypre','🇨🇾','Asia'),
('GE','Géorgie','🇬🇪','Asia'),
('IN','Inde','🇮🇳','Asia'),
('ID','Indonésie','🇮🇩','Asia'),
('IR','Iran','🇮🇷','Asia'),
('IQ','Irak','🇮🇶','Asia'),
('IL','Israël','🇮🇱','Asia'),
('JP','Japon','🇯🇵','Asia'),
('JO','Jordanie','🇯🇴','Asia'),
('KZ','Kazakhstan','🇰🇿','Asia'),
('KW','Koweït','🇰🇼','Asia'),
('KG','Kirghizistan','🇰🇬','Asia'),
('LA','Laos','🇱🇦','Asia'),
('LB','Liban','🇱🇧','Asia'),
('MY','Malaisie','🇲🇾','Asia'),
('MV','Maldives','🇲🇻','Asia'),
('MN','Mongolie','🇲🇳','Asia'),
('MM','Myanmar','🇲🇲','Asia'),
('NP','Népal','🇳🇵','Asia'),
('OM','Oman','🇴🇲','Asia'),
('PK','Pakistan','🇵🇰','Asia'),
('PH','Philippines','🇵🇭','Asia'),
('QA','Qatar','🇶🇦','Asia'),
('SA','Arabie saoudite','🇸🇦','Asia'),
('SG','Singapour','🇸🇬','Asia'),
('KR','Corée du Sud','🇰🇷','Asia'),
('LK','Sri Lanka','🇱🇰','Asia'),
('SY','Syrie','🇸🇾','Asia'),
('TJ','Tadjikistan','🇹🇯','Asia'),
('TH','Thaïlande','🇹🇭','Asia'),
('TL','Timor oriental','🇹🇱','Asia'),
('TR','Turquie','🇹🇷','Asia'),
('TM','Turkménistan','🇹🇲','Asia'),
('AE','Émirats arabes unis','🇦🇪','Asia'),
('UZ','Ouzbékistan','🇺🇿','Asia'),
('VN','Vietnam','🇻🇳','Asia'),
('AU','Australie','🇦🇺','Oceania'),
('FJ','Fidji','🇫🇯','Oceania'),
('KI','Kiribati','🇰🇮','Oceania'),
('MH','Îles Marshall','🇲🇭','Oceania'),
('FM','Micronésie','🇫🇲','Oceania'),
('NR','Nauru','🇳🇷','Oceania'),
('NZ','Nouvelle-Zélande','🇳🇿','Oceania'),
('PW','Palaos','🇵🇼','Oceania'),
('PG','Papouasie-Nouvelle-Guinée','🇵🇬','Oceania'),
('WS','Samoa','🇼🇸','Oceania'),
('SB','Îles Salomon','🇸🇧','Oceania'),
('TO','Tonga','🇹🇴','Oceania'),
('TV','Tuvalu','🇹🇻','Oceania'),
('VU','Vanuatu','🇻🇺','Oceania');