INSERT INTO country (code,name,emoji,continent) VALUES
('AL','Albanie','🇦🇱','Europe'),
('AT','Autriche','🇦🇹','Europe'),
('BY','Biélorussie','🇧🇾','Europe'),
('BE','Belgique','🇧🇪','Europe'),
('BA','Bosnie-Herzégovine','🇧🇦','Europe'),
('BG','Bulgarie','🇧🇬','Europe'),
('HR','Croatie','🇭🇷','Europe'),
('CY','Chypre','🇨🇾','Europe'),
('CZ','République tchèque','🇨🇿','Europe'),
('DK','Danemark','🇩🇰','Europe'),
('EE','Estonie','🇪🇪','Europe'),
('FI','Finlande','🇫🇮','Europe'),
('FR','France','🇫🇷','Europe'),
('DE','Allemagne','🇩🇪','Europe'),
('GR','Grèce','🇬🇷','Europe'),
('HU','Hongrie','🇭🇺','Europe'),
('IS','Islande','🇮🇸','Europe'),
('IE','Irlande','🇮🇪','Europe'),
('IT','Italie','🇮🇹','Europe'),
('LV','Lettonie','🇱🇻','Europe'),
('LI','Liechtenstein','🇱🇮','Europe'),
('LT','Lituanie','🇱🇹','Europe'),
('LU','Luxembourg','🇱🇺','Europe'),
('MT','Malte','🇲🇹','Europe'),
('MD','Moldavie','🇲🇩','Europe'),
('MC','Monaco','🇲🇨','Europe'),
('ME','Monténégro','🇲🇪','Europe'),
('NL','Pays-Bas','🇳🇱','Europe'),
('MK','Macédoine du Nord','🇲🇰','Europe'),
('NO','Norvège','🇳🇴','Europe'),
('PL','Pologne','🇵🇱','Europe'),
('PT','Portugal','🇵🇹','Europe'),
('RO','Roumanie','🇷🇴','Europe'),
('RU','Russie','🇷🇺','Europe'),
('SM','Saint-Marin','🇸🇲','Europe'),
('RS','Serbie','🇷🇸','Europe'),
('SK','Slovaquie','🇸🇰','Europe'),
('SI','Slovénie','🇸🇮','Europe'),
('ES','Espagne','🇪🇸','Europe'),
('SE','Suède','🇸🇪','Europe'),
('CH','Suisse','🇨🇭','Europe'),
('TR','Turquie','🇹🇷','Europe'),
('UA','Ukraine','🇺🇦','Europe'),
('GB','Royaume-Uni','🇬🇧','Europe'),
('AG','Antigua-et-Barbuda','🇦🇬','North America'),
('BS','Bahamas','🇧🇸','Amérique du Nord'),
('BB','Barbade','🇧🇧','Amérique du Nord'),
('BZ','Belize','🇧🇿','Amérique du Nord'),
('CA','Canada','🇨🇦','Amérique du Nord'),
('CR','Costa Rica','🇨🇷','Amérique du Nord'),
('CU','Cuba','🇨🇺','Amérique du Nord'),
('DM','Dominique','🇩🇲','Amérique du Nord'),
('DO','République dominicaine','🇩🇴','Amérique du Nord'),
('SV','Salvador','🇸🇻','Amérique du Nord'),
('GD','Grenade','🇬🇩','Amérique du Nord'),
('GT','Guatemala','🇬🇹','Amérique du Nord'),
('HT','Haïti','🇭🇹','Amérique du Nord'),
('HN','Honduras','🇭🇳','Amérique du Nord'),
('JM','Jamaïque','🇯🇲','Amérique du Nord'),
('MX','Mexique','🇲🇽','Amérique du Nord'),
('NI','Nicaragua','🇳🇮','Amérique du Nord'),
('PA','Panama','🇵🇦','Amérique du Nord'),
('KN','Saint-Christophe-et-Niévès','🇰🇳','Amérique du Nord'),
('LC','Sainte-Lucie','🇱🇨','Amérique du Nord'),
('VC','Saint-Vincent-et-les-Grenadines','🇻🇨','Amérique du Nord'),
('TT','Trinité-et-Tobago','🇹🇹','Amérique du Nord'),
('AR','Argentine','🇦🇷','Amérique du Sud'),
('BO','Bolivie','🇧🇴','Amérique du Sud'),
('BR','Brésil','🇧🇷','Amérique du Sud'),
('CL','Chili','🇨🇱','Amérique du Sud'),
('CO','Colombie','🇨🇴','Amérique du Sud'),
('EC','Équateur','🇪🇨','Amérique du Sud'),
('GY','Guyana','🇬🇾','Amérique du Sud'),
('PY','Paraguay','🇵🇾','Amérique du Sud'),
('PE','Pérou','🇵🇪','Amérique du Sud'),
('SR','Suriname','🇸🇷','Amérique du Sud'),
('UY','Uruguay','🇺🇾','Amérique du Sud'),
('DZ','Algérie','🇩🇿','Afrique'),
('AO','Angola','🇦🇴','Afrique'),
('BJ','Bénin','🇧🇯','Afrique'),
('BW','Botswana','🇧🇼','Afrique'),
('BF','Burkina Faso','🇧🇫','Afrique'),
('BI','Burundi','🇧🇮','Afrique'),
('CM','Cameroun','🇨🇲','Afrique'),
('CV','Cap-Vert','🇨🇻','Afrique'),
('CF','République centrafricaine','🇨🇫','Afrique'),
('TD','Tchad','🇹🇩','Afrique'),
('KM','Comores','🇰🇲','Afrique'),
('CG','Congo','🇨🇬','Afrique'),
('CD','République démocratique du Congo','🇨🇩','Afrique'),
('CI','Côte d''Ivoire','🇨🇮','Afrique'),
('DJ','Djibouti','🇩🇯','Afrique'),
('EG','Égypte','🇪🇬','Afrique'),
('GQ','Guinée équatoriale','🇬🇶','Afrique'),
('ER','Érythrée','🇪🇷','Afrique'),
('SZ','Eswatini','🇸🇿','Afrique'),
('ET','Éthiopie','🇪🇹','Afrique'),
('GA','Gabon','🇬🇦','Afrique'),
('GM','Gambie','🇬🇲','Afrique'),
('GH','Ghana','🇬🇭','Afrique'),
('GN','Guinée','🇬🇳','Afrique'),
('GW','Guinée-Bissau','🇬🇼','Afrique'),
('KE','Kenya','🇰🇪','Afrique'),
('LS','Lesotho','🇱🇸','Afrique'),
('LR','Libéria','🇱🇷','Afrique'),
('LY','Libye','🇱🇾','Afrique'),
('MG','Madagascar','🇲🇬','Afrique'),
('MW','Malawi','🇲🇼','Afrique'),
('ML','Mali','🇲🇱','Afrique'),
('MR','Mauritanie','🇲🇷','Afrique'),
('MU','Maurice','🇲🇺','Afrique'),
('MA','Maroc','🇲🇦','Afrique'),
('MZ','Mozambique','🇲🇿','Afrique'),
('NA','Namibie','🇳🇦','Afrique'),
('NE','Niger','🇳🇪','Afrique'),
('NG','Nigéria','🇳🇬','Afrique'),
('RW','Rwanda','🇷🇼','Afrique'),
('ST','Sao Tomé-et-Principe','🇸🇹','Afrique'),
('SN','Sénégal','🇸🇳','Afrique'),
('SC','Seychelles','🇸🇨','Afrique'),
('SL','Sierra Leone','🇸🇱','Afrique'),
('SO','Somalie','🇸🇴','Afrique'),
('ZA','Afrique du Sud','🇿🇦','Afrique'),
('SS','Soudan du Sud','🇸🇸','Afrique'),
('SD','Soudan','🇸🇩','Afrique'),
('TZ','Tanzanie','🇹🇿','Afrique'),
('TG','Togo','🇹🇬','Afrique'),
('TN','Tunisie','🇹🇳','Afrique'),
('UG','Ouganda','🇺🇬','Afrique'),
('ZM','Zambie','🇿🇲','Afrique'),
('AQ','Antarctique','🇦🇶','Antarctique'),
('BV','Île Bouvet','🇧🇻','Antarctique'),
('TF','Terres australes et antarctiques françaises','🇹🇫','Antarctique'),
('HM','Îles Heard-et-MacDonald','🇭🇲','Antarctique'),
('AF','Afghanistan','🇦🇫','Asie'),
('AM','Arménie','🇦🇲','Asie'),
('AZ','Azerbaïdjan','🇦🇿','Asie'),
('BH','Bahreïn','🇧🇭','Asie'),
('BD','Bangladesh','🇧🇩','Asie'),
('BT','Bhoutan','🇧🇹','Asie'),
('BN','Brunei','🇧🇳','Asie'),
('KH','Cambodge','🇰🇭','Asie'),
('CN','Chine','🇨🇳','Asie'),
('CY','Chypre','🇨🇾','Asie'),
('GE','Géorgie','🇬🇪','Asie'),
('IN','Inde','🇮🇳','Asie'),
('ID','Indonésie','🇮🇩','Asie'),
('IR','Iran','🇮🇷','Asie'),
('IQ','Irak','🇮🇶','Asie'),
('IL','Israël','🇮🇱','Asie'),
('JP','Japon','🇯🇵','Asie'),
('JO','Jordanie','🇯🇴','Asie'),
('KZ','Kazakhstan','🇰🇿','Asie'),
('KW','Koweït','🇰🇼','Asie'),
('KG','Kirghizistan','🇰🇬','Asie'),
('LA','Laos','🇱🇦','Asie'),
('LB','Liban','🇱🇧','Asie'),
('MY','Malaisie','🇲🇾','Asie'),
('MV','Maldives','🇲🇻','Asie'),
('MN','Mongolie','🇲🇳','Asie'),
('MM','Myanmar','🇲🇲','Asie'),
('NP','Népal','🇳🇵','Asie'),
('OM','Oman','🇴🇲','Asie'),
('PK','Pakistan','🇵🇰','Asie'),
('PH','Philippines','🇵🇭','Asie'),
('QA','Qatar','🇶🇦','Asie'),
('SA','Arabie saoudite','🇸🇦','Asie'),
('SG','Singapour','🇸🇬','Asie'),
('KR','Corée du Sud','🇰🇷','Asie'),
('LK','Sri Lanka','🇱🇰','Asie'),
('SY','Syrie','🇸🇾','Asie'),
('TJ','Tadjikistan','🇹🇯','Asie'),
('TH','Thaïlande','🇹🇭','Asie'),
('TL','Timor oriental','🇹🇱','Asie'),
('TR','Turquie','🇹🇷','Asie'),
('TM','Turkménistan','🇹🇲','Asie'),
('AE','Émirats arabes unis','🇦🇪','Asie'),
('UZ','Ouzbékistan','🇺🇿','Asie'),
('VN','Vietnam','🇻🇳','Asie'),
('AU','Australie','🇦🇺','Océanie'),
('FJ','Fidji','🇫🇯','Océanie'),
('KI','Kiribati','🇰🇮','Océanie'),
('MH','Îles Marshall','🇲🇭','Océanie'),
('FM','Micronésie','🇫🇲','Océanie'),
('NR','Nauru','🇳🇷','Océanie'),
('NZ','Nouvelle-Zélande','🇳🇿','Océanie'),
('PW','Palaos','🇵🇼','Océanie'),
('PG','Papouasie-Nouvelle-Guinée','🇵🇬','Océanie'),
('WS','Samoa','🇼🇸','Océanie'),
('SB','Îles Salomon','🇸🇧','Océanie'),
('TO','Tonga','🇹🇴','Océanie'),
('TV','Tuvalu','🇹🇻','Océanie'),
('VU','Vanuatu','🇻🇺','Océanie');

